// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestOrigin.DAL;

namespace TestOrigin.DAL.Migrations
{
    [DbContext(typeof(ATMContext))]
    partial class ATMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestOrigin.Domain.Entities.Balance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaOperacion");

                    b.Property<int>("TarjetaId");

                    b.HasKey("BalanceId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("TestOrigin.Domain.Entities.Retiro", b =>
                {
                    b.Property<int>("RetiroId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CantidadOperada")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("FechaOperacion");

                    b.Property<int>("TarjetaId");

                    b.HasKey("RetiroId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("Retiros");
                });

            modelBuilder.Entity("TestOrigin.Domain.Entities.Tarjeta", b =>
                {
                    b.Property<int>("TarjetaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("Bloqueada");

                    b.Property<DateTime>("FechaVencimiento");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<int>("PIN");

                    b.Property<int>("Reintentos");

                    b.HasKey("TarjetaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("TestOrigin.Domain.Entities.Balance", b =>
                {
                    b.HasOne("TestOrigin.Domain.Entities.Tarjeta", "BalanceTarjeta")
                        .WithMany()
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestOrigin.Domain.Entities.Retiro", b =>
                {
                    b.HasOne("TestOrigin.Domain.Entities.Tarjeta", "RetiroTarjeta")
                        .WithMany()
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
